<?php

namespace App\Nova\Dashboards;

use App\Nova\Comment;
use App\Nova\Metrics\NewBoxes;
use App\Nova\Metrics\NewBoxesPerDay;
use App\Nova\Metrics\NewBoxesProgress;
use App\Nova\Metrics\NewComments;
use App\Nova\Metrics\NewUsers;
use Laravel\Nova\Cards\Help;
use Laravel\Nova\Dashboards\Main as Dashboard;

class Main extends Dashboard
{
    public function name()
    {
        return 'Overview'; // TODO: Change the autogenerated stub
    }


    /**
     * Get the cards for the dashboard.
     *
     * @return array
     */
    public function cards()
    {
        return [
            new NewUsers(),
            new NewBoxes(),
            new NewBoxesPerDay(),
            new NewBoxesProgress(),
            new NewComments()
        ];
    }
}
